### ISSUE TITLE
<bug> database.yml resetting

### ISSUE THREAD

**Issue by madtomic** [filoghost/TouchscreenHolograms#2]
database.yml is resetting when server is restarted. 

Using 
[18:35:57 INFO]: [TouchscreenHolograms] Loading TouchscreenHolograms v1.3.2

**Comment by madtomic** [comment]
I think I found the issue. You're plugin is not finding the hologram from HD when it loads up so it is removing them. Can you fix this please.

**Comment by Pawned** [comment]
I am getting the same issue, can this be looked into please :/?

**Comment by filoghost** [comment]
Please update the plugin, v1.4.0+ doesn't have this problem.
