### ISSUE TITLE
Touchscreen Holograms won't recognize Holographic Display version, even though it's the latest

### ISSUE THREAD

**Issue by jusobreira** [filoghost/TouchscreenHolograms#5]
Touchscreen Holograms won't recognize Holographic Display version, even though it's the latest

![image](https://user-images.githubusercontent.com/10175304/88599734-d9e05c80-d042-11ea-8e61-e24e999c7b3b.png)
![image](https://user-images.githubusercontent.com/10175304/88599752-e5cc1e80-d042-11ea-92d2-4c9b3df09b48.png)
![image](https://user-images.githubusercontent.com/10175304/88599888-49564c00-d043-11ea-9ed2-c42aca973739.png)
![image](https://user-images.githubusercontent.com/10175304/88599926-5d9a4900-d043-11ea-89b9-16085edf403a.png)

**Comment by filoghost** [comment]
Better late than never, sorry for not answering. Fixed in v1.4.3.
