### ISSUE TITLE
Holographic Touch doesn't work and recognise holographic displays 

### ISSUE THREAD

**Issue by heyitscalz** [filoghost/TouchscreenHolograms#6]
I am running a paper 1.13.2 server and with the latest Holographcs Displays I get this error.

03.08 12:46:36 [Server] INFO [TouchscreenHolograms] Enabling TouchscreenHolograms v1.4.2
03.08 12:46:36 [Server] INFO ******************************************************
03.08 12:46:36 [Server] INFO TouchscreenHolograms requires the plugin
03.08 12:46:36 [Server] INFO HolographicDisplays v2.0+ enabled to run.
03.08 12:46:36 [Server] INFO This plugin will be disabled.
03.08 12:46:36 [Server] INFO ******************************************************

**Comment by filoghost** [comment]
Please see #5, sorry for answering late.
