### ISSUE TITLE
Touch Doesn't work.

### ISSUE THREAD

**Issue by CraXyOW3** [filoghost/TouchscreenHolograms#7]
Everything installs just fine and is loaded in console.
I can add commands and everything but nothing executes when/however i click on the hologram.

Running 1.17.1 with lates Holographic Displays, latest bungeecord
I can not see any other errors anywhere, even the log files.

**Comment by Aquaticz24** [comment]
Have you found a fix yet?

**Comment by TeddMC** [comment]
Same issue, updated from 1.16.5 -> 1.17.1 and it no longer works, no errors however

**Comment by filoghost** [comment]
Please try with Holographic Displays v3 and the latest version of Touchscreen Holograms. Apologies for answering so late.
