### ISSUE TITLE
Update for HolographicDisplays v3

### ISSUE THREAD

**Issue by Trikolon** [filoghost/TouchscreenHolograms#8]
TouchscreenHolograms needs to be updated to support the new API of HolographicDisplays v3.

**Comment by sphings79** [comment]
+1

**Comment by rafi67000** [comment]
+1

**Comment by DarkAshOP** [comment]
+1

**Comment by Psykrot** [comment]
+1

**Comment by sphings79** [comment]
Since nothing happened here. I switched over to decentholograms.

**Comment by filoghost** [comment]
It is now updated. Some internal details of the new Holographic Displays were still changing, as v3 is not fully released yet.
